name: Mesin Pembuat APK

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Nama Aplikasi'
        required: true
        default: 'TokoSaya'
      web_url:
        description: 'URL Website Klien'
        required: true
        default: 'https://google.com'

jobs:
  build-apk:
    name: Proses Pembuatan APK
    runs-on: ubuntu-latest

    steps:
      - name: 1. Tarik Kode Template
        uses: actions/checkout@v4

      - name: 2. Siapkan Komputer Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: 3. Beri Izin Eksekusi Gradle
        run: chmod +x ./gradlew

      - name: 4. Suntikkan Nama Aplikasi & URL Klien ke dalam Kode
        # Ini adalah proses 'Find and Replace' otomatis menggunakan perintah Linux 'sed'
        run: |
          sed -i "s|TEMPLATE_NAMA_APP|${{ github.event.inputs.app_name }}|g" app/src/main/res/values/strings.xml
          sed -i "s|TEMPLATE_URL_WEB|${{ github.event.inputs.web_url }}|g" app/src/main/java/com/domain/anda/MainActivity.java

      - name: 5. Mulai Merakit APK (Build Process)
        run: ./gradlew assembleDebug

      - name: 6. Simpan File APK yang Sudah Jadi
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.app_name }}-app
          path: app/build/outputs/apk/debug/app-debug.apk
